CREATE TABLE PESSOA
(
 NOME VARCHAR2(200) NOT NULL,
 CPF VARCHAR2(11) NOT NULL,
 CONSTRAINT PESSOA_PK PRIMARY KEY 
    (
        CPF
    )
    ENABLE
 
);


CREATE TABLE CAFEMANHA
(
 COD_OPCAO NUMBER NOT NULL,
 OPCAO VARCHAR2(100) NOT NULL,
 CPF_PESSOA VARCHAR2(11),
 CONSTRAINT FK_CPF_PESSOA FOREIGN KEY(CPF_PESSOA) REFERENCES PESSOA(CPF),
 CONSTRAINT U_OPCAO UNIQUE(OPCAO),
 CONSTRAINT CAFEMANHA_PK PRIMARY KEY 
    (
        COD_OPCAO
    )
    
    ENABLE
 
);

CREATE SEQUENCE S_COD_OPCAO INCREMENT BY 1 START WITH 1 MINVALUE 1;

CREATE OR REPLACE TRIGGER T_COD_OPCAO
BEFORE INSERT ON CAFEMANHA
    FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            IF :NEW.COD_OPCAO IS NULL THEN
                SELECT S_COD_OPCAO.NEXTVAL INTO :NEW.COD_OPCAO FROM DUAL;
            END IF;
        END IF;
    END;